# src https://docs.gitlab.com/ce/ci/examples/test-and-deploy-python-application-to-heroku.html
# src https://gitlab.com/help/ci/quick_start/README

# version used for develop the application (production is going to use python3.5)
image: python:3.6-stretch

# src https://gitlab.com/gitlab-examples/postgres/blob/master/.gitlab-ci.yml
services:
  - postgres:9.6    # debian stable version of postgresql

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# thanks https://fleschenberg.net/gitlab-pip-cache/
# extra src https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Django.gitlab-ci.yml
# extra src https://gitlab.com/gableroux/gitlab-ci-example-django/blob/master/.gitlab-ci.yml
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

test:
  before_script:
    - python3 -V   # Print out python version for debugging
    - pip3 install . # add linguatec_lexicon to PYTHONPATH
    - pip3 install -r tests/requirements.txt
    - pip3 install psycopg2-binary # postgresql client
  variables:
    DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  script:
  - ./runtests.py --settings tests.test_postgres
