# src https://docs.gitlab.com/ce/ci/examples/test-and-deploy-python-application-to-heroku.html
# src https://gitlab.com/help/ci/quick_start/README

test:
  script:
  - apt-get update -qy
  - apt-get install -y --no-install-recommends python3-pip
  # temp: quit virtualenv when possible
  - pip3 install virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip3 install -r requirements.txt
  - pip3 install . # add linguatec_lexicon to PYTHONPATH
  - django-admin startproject testsite --template=linguatec_lexicon/conf/project_template
#  - mv testsite/testsite/settings.py testsite/testsite/settings.py.orig
#  - cp test/settings_test.py testsite/testsite/settings.py
  - cd testsite
  - python manage.py migrate
  - python manage.py test linguatec_lexicon

staging:
  type: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
  - apt-get update -qy
  - apt-get install -y --no-install-recommends python3-pip
  - ssh -p22 linguatec@api.conectividadcolectiva.org "rm -rf linguatec-lexicon/"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "mkdir -p linguatec-lexicon/sandbox"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "git clone git@gitlab.com:linguatec/linguatec-lexicon.git linguatec-lexicon/source"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "virtualenv -p /usr/bin/python3 linguatec-lexicon/env"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "linguatec-lexicon/env/bin/pip install -r linguatec-lexicon/source/requirements.txt"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "linguatec-lexicon/env/bin/pip install -e linguatec-lexicon/source/"
  # Requires to have a properly configured django project at ~/sandbox
  - ssh -p22 linguatec@api.conectividadcolectiva.org "linguatec-lexicon/env/bin/python ~/sandbox/manage.py migrate --noinput"
  - ssh -p22 linguatec@api.conectividadcolectiva.org "linguatec-lexicon/env/bin/python ~/sandbox/manage.py collectstatic --noinput"
  # TODO reload apache2
  only:
  - master
