
name: runtests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:  
        image: mdillon/postgis:10
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_lexicon
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          sudo apt-get install --no-install-recommends python3-pip
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install coverage
          pip3 install -r requirements.txt
          pip3 install -e .
          
          
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      #- name: Run migrations
      #   run: python3 manage.py migrate
      - name: Run tests
        run: |
          coverage run --source linguatec_lexicon runtests.py --settings tests.settings_postgres --parallel 1
          coverage html
        
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
